
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Course Level
 *
 * Codename: course_level
 * Id: 37f29dd0-351d-4f8d-8be5-6cca5424ea14
 */
export const courseLevelValues = ["beginner", "intermediate"] as const;

/**
 * Type representing Course Level taxonomy
 *
 * Codename: course_level
 * Id: 37f29dd0-351d-4f8d-8be5-6cca5424ea14
 */
export type CourseLevel = (typeof courseLevelValues)[number];

/**
 * Type guard for Course Level
 *
 * Codename: course_level
 * Id: 37f29dd0-351d-4f8d-8be5-6cca5424ea14
 */
export function isCourseLevel(value: string | undefined | null): value is CourseLevel {
  return typeof value === "string" && (courseLevelValues as readonly string[]).includes(value);
}
