
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Topics
 *
 * Codename: topics
 * Id: f13b8bcb-e4ff-4937-b002-6f262d437580
 */
export const topicsValues = [
  "what_s_new_",
  "honeybook_ai",
  "automations",
  "branding",
  "client_portal",
  "clients",
  "contact_forms",
  "emails",
  "files",
  "finance",
  "integrations",
  "honeybook_features",
  "capture_business",
  "qualifying_leads",
  "book_clients",
  "manage_clients___projects",
  "maintain_relationships",
  "client_stages",
  "podcast_episodes",
  "business_education",
  "release_notes",
] as const;

/**
 * Type representing Topics taxonomy
 *
 * Codename: topics
 * Id: f13b8bcb-e4ff-4937-b002-6f262d437580
 */
export type Topics = (typeof topicsValues)[number];

/**
 * Type guard for Topics
 *
 * Codename: topics
 * Id: f13b8bcb-e4ff-4937-b002-6f262d437580
 */
export function isTopics(value: string | undefined | null): value is Topics {
  return typeof value === "string" && (topicsValues as readonly string[]).includes(value);
}
