
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Tab } from "./index.ts";

/**
 * ➕ Tabs Section
 *
 * Id: a986a125-eb52-49c2-a910-3fc50e133842
 * Codename: __accordion__copy_
 */
export type TabsSection = CoreContentType<
  TabsSectionElementCodenames,
  {
    /**
     * Tabs
     *
     * Type: modular_content
     * Required: false
     * Codename: tabs
     * Id: cda266ab-fa59-4466-9098-75be0f4210f5
     */
    readonly tabs: Elements.LinkedItemsElement<Tab>;
  },
  "__accordion__copy_"
>;

/**
 * Type representing all available element codenames for ➕ Tabs Section
 */
export type TabsSectionElementCodenames = "tabs";

/**
 * Type guard for ➕ Tabs Section
 *
 * Id: a986a125-eb52-49c2-a910-3fc50e133842
 * Codename: __accordion__copy_
 */
export function isTabsSection(item: CoreContentType | undefined | null): item is TabsSection {
  return item?.system?.type === "__accordion__copy_";
}
