
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ➕ Cloudinary Asset
 *
 * Id: 11e31562-9a25-4e0f-8548-c3fd841e9829
 * Codename: cloudinary_asset
 */
export type CloudinaryAsset = CoreContentType<
  CloudinaryAssetElementCodenames,
  {
    /**
     * Video from Cloudinary
     *
     * Type: custom
     * Required: false
     * Codename: video_from_cloudinary
     * Id: b7af88e3-9ed1-41c3-aa88-9a36c58918c3
     */
    readonly video_from_cloudinary: Elements.CustomElement;
  },
  "cloudinary_asset"
>;

/**
 * Type representing all available element codenames for ➕ Cloudinary Asset
 */
export type CloudinaryAssetElementCodenames = "video_from_cloudinary";

/**
 * Type guard for ➕ Cloudinary Asset
 *
 * Id: 11e31562-9a25-4e0f-8548-c3fd841e9829
 * Codename: cloudinary_asset
 */
export function isCloudinaryAsset(item: CoreContentType | undefined | null): item is CloudinaryAsset {
  return item?.system?.type === "cloudinary_asset";
}
