
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { CourseLevel, Topics } from "../taxonomies/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Person } from "./index.ts";

/**
 * ✏️ Course
 *
 * Id: 69657765-3ca1-4b1e-9bc3-6db11d514823
 * Codename: course
 */
export type Course = CoreContentType<
  CourseElementCodenames,
  {
    /**
     * Course Title
     *
     * Type: text
     * Required: false
     * Codename: course_title
     * Id: 6154d1ae-de00-4915-8ecd-f38dd20548e1
     */
    readonly course_title: Elements.TextElement;
    /**
     * Summary
     *
     * Type: rich_text
     * Required: false
     * Codename: summary
     * Id: b77d5273-f0a7-4de5-9b47-3e06c60be06c
     */
    readonly summary: Elements.RichTextElement<CoreContentType>;
    /**
     * Content
     *
     * Type: rich_text
     * Required: false
     * Codename: course_body
     * Id: 675e4484-8130-42f8-9360-ac684d09fb0f
     */
    readonly course_body: Elements.RichTextElement<CoreContentType>;
    /**
     * Length
     *
     * Type: number
     * Required: false
     * Codename: length
     * Id: b7c54de3-4f2d-495c-8ac8-cb947fa74cc7
     * Guidelines: How long should the course take to complete (in minutes).
     */
    readonly length: Elements.NumberElement;
    /**
     * Course Image
     *
     * Type: asset
     * Required: false
     * Codename: course_image
     * Id: d8e34f38-0312-45d2-8105-dddc547c662e
     */
    readonly course_image: Elements.AssetsElement;
    /**
     * Course Level
     *
     * Type: taxonomy
     * Required: false
     * Codename: course_level
     * Id: 0c99f878-30f9-41be-b51d-eee1fff90b02
     */
    readonly course_level: Elements.TaxonomyElement<CourseLevel, "course_level">;
    /**
     * Topics
     *
     * Type: taxonomy
     * Required: false
     * Codename: topics
     * Id: 21cfea5c-cb58-4341-b832-039ab165703c
     */
    readonly topics: Elements.TaxonomyElement<Topics, "topics">;
    /**
     * Course Author
     *
     * Type: modular_content
     * Required: false
     * Codename: course_author
     * Id: d702b261-e223-460e-9bad-623b40cf6218
     */
    readonly course_author: Elements.LinkedItemsElement<Person>;
    /**
     * URL
     *
     * Type: url_slug
     * Required: true
     * Codename: url
     * Id: 481aeb4a-c78c-4a0c-bd91-01c490612504
     */
    readonly url: Elements.UrlSlugElement;
  } & Metadata,
  "course"
>;

/**
 * Type representing all available element codenames for ✏️ Course
 */
export type CourseElementCodenames =
  | "course_title"
  | "summary"
  | "course_body"
  | "length"
  | "course_image"
  | "course_level"
  | "topics"
  | "course_author"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url";

/**
 * Type guard for ✏️ Course
 *
 * Id: 69657765-3ca1-4b1e-9bc3-6db11d514823
 * Codename: course
 */
export function isCourse(item: CoreContentType | undefined | null): item is Course {
  return item?.system?.type === "course";
}
