
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { CourseLevel } from "../taxonomies/index.ts";
import type { Person, FAQSection } from "./index.ts";

/**
 * Event
 *
 * Id: e97907ba-c5ae-53e6-bcb6-091bc89da3fa
 * Codename: event
 */
export type Event = CoreContentType<
  EventElementCodenames,
  {
    /**
     * Name
     *
     * Type: text
     * Required: true
     * Codename: name
     * Id: 60502ad7-d552-5435-af46-6f4df84c3ddd
     */
    readonly name: Elements.TextElement;
    /**
     * Instructor
     *
     * Type: modular_content
     * Required: false
     * Codename: instructor
     * Id: ee9877b9-3db0-4eb8-8461-8442f812f356
     * Guidelines: Who is leading the event?
     */
    readonly instructor: Elements.LinkedItemsElement<Person>;
    /**
     * Class Length
     *
     * Type: number
     * Required: true
     * Codename: class_length
     * Id: a66eeb79-bc1f-4a7d-96c3-4c3deb8e3b59
     * Guidelines: Write the number in minutes (Ex. 60)
     */
    readonly class_length: Elements.NumberElement;
    /**
     * Course Level
     *
     * Type: taxonomy
     * Required: true
     * Codename: course_level
     * Id: 1252e7c2-4931-4e21-827c-96f275bf5c65
     */
    readonly course_level: Elements.TaxonomyElement<CourseLevel, "course_level">;
    /**
     * Frequency
     *
     * Type: multiple_choice
     * Required: false
     * Codename: frequency
     * Id: 0b11b045-51bf-496b-8d62-0a5bdc39a4a9
     */
    readonly frequency: Elements.MultipleChoiceElement<"weekly" | "monthly" | "once">;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: b13e797e-0e50-5ecb-aebc-05aa9e180864
     */
    readonly image: Elements.AssetsElement;
    /**
     * Start Date
     *
     * Type: date_time
     * Required: true
     * Codename: start_date
     * Id: 114ba02d-f9dd-5555-a78d-6798d1a835a0
     */
    readonly start_date: Elements.DateTimeElement;
    /**
     * End Date
     *
     * Type: date_time
     * Required: false
     * Codename: end_date
     * Id: a00fecf1-c7ff-5bed-8c40-2eba7460170a
     */
    readonly end_date: Elements.DateTimeElement;
    /**
     * Description
     *
     * Type: rich_text
     * Required: true
     * Codename: description
     * Id: 2a7a8e84-274c-5339-afd2-4865b643fbb2
     */
    readonly description: Elements.RichTextElement<CoreContentType>;
    /**
     * What We'll Cover
     *
     * Type: rich_text
     * Required: false
     * Codename: what_we_ll_cover
     * Id: 0a8ceb5e-b8cb-4cde-87f2-9c490083b594
     */
    readonly what_we_ll_cover: Elements.RichTextElement<CoreContentType>;
    /**
     * Why It Matters
     *
     * Type: rich_text
     * Required: false
     * Codename: why_it_matters
     * Id: 70975439-a1c9-45d4-afaa-c083a261407f
     */
    readonly why_it_matters: Elements.RichTextElement<CoreContentType>;
    /**
     * FAQ Section
     *
     * Type: modular_content
     * Required: false
     * Codename: faq_section
     * Id: fb7d0300-e1cd-4d79-9903-13c0a1fb4e4e
     */
    readonly faq_section: Elements.LinkedItemsElement<FAQSection>;
  },
  "event"
>;

/**
 * Type representing all available element codenames for Event
 */
export type EventElementCodenames =
  | "name"
  | "instructor"
  | "class_length"
  | "course_level"
  | "frequency"
  | "image"
  | "start_date"
  | "end_date"
  | "description"
  | "what_we_ll_cover"
  | "why_it_matters"
  | "faq_section";

/**
 * Type guard for Event
 *
 * Id: e97907ba-c5ae-53e6-bcb6-091bc89da3fa
 * Codename: event
 */
export function isEvent(item: CoreContentType | undefined | null): item is Event {
  return item?.system?.type === "event";
}
