
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ➕ FAQ
 *
 * Id: 00ee212c-0264-4254-bbe8-0a090c15a183
 * Codename: faq
 */
export type FAQ = CoreContentType<
  FAQElementCodenames,
  {
    /**
     * Question
     *
     * Type: text
     * Required: false
     * Codename: question
     * Id: 9ca7352b-1102-4588-b770-73fe3a7c32e0
     */
    readonly question: Elements.TextElement;
    /**
     * Answer
     *
     * Type: text
     * Required: false
     * Codename: answer
     * Id: 6d002265-ff76-4539-b32b-37b2627f3e79
     */
    readonly answer: Elements.TextElement;
  },
  "faq"
>;

/**
 * Type representing all available element codenames for ➕ FAQ
 */
export type FAQElementCodenames = "question" | "answer";

/**
 * Type guard for ➕ FAQ
 *
 * Id: 00ee212c-0264-4254-bbe8-0a090c15a183
 * Codename: faq
 */
export function isFAQ(item: CoreContentType | undefined | null): item is FAQ {
  return item?.system?.type === "faq";
}
