
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { FAQ } from "./index.ts";

/**
 * FAQ Section
 *
 * Id: a21a62ca-e146-493d-9a94-9d4b6e4ba1fc
 * Codename: faq_section
 */
export type FAQSection = CoreContentType<
  FAQSectionElementCodenames,
  {
    /**
     * FAQs
     *
     * Type: modular_content
     * Required: false
     * Codename: faqs
     * Id: a0f4f93b-28ea-4abf-b32f-ad4c05e6d087
     */
    readonly faqs: Elements.LinkedItemsElement<FAQ>;
  },
  "faq_section"
>;

/**
 * Type representing all available element codenames for FAQ Section
 */
export type FAQSectionElementCodenames = "faqs";

/**
 * Type guard for FAQ Section
 *
 * Id: a21a62ca-e146-493d-9a94-9d4b6e4ba1fc
 * Codename: faq_section
 */
export function isFAQSection(item: CoreContentType | undefined | null): item is FAQSection {
  return item?.system?.type === "faq_section";
}
