
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Video, Disclaimer, CallToAction, Course, CloudinaryAsset } from "./index.ts";

/**
 * 🏠 Landing Page
 *
 * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
 * Codename: landing_page
 */
export type LandingPage = CoreContentType<
  LandingPageElementCodenames,
  {
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: false
     * Codename: body_copy
     * Id: 7b9826ff-5cb0-450f-b16a-bd176aed04cf
     */
    readonly body_copy: Elements.RichTextElement<Video | Disclaimer | CallToAction>;
    /**
     * Featured Courses
     *
     * Type: modular_content
     * Required: false
     * Codename: featured_courses
     * Id: fda97e1d-79aa-4b5c-91e5-3c83726a3a8e
     */
    readonly featured_courses: Elements.LinkedItemsElement<Course>;
    /**
     * Upcoming Events
     *
     * Type: modular_content
     * Required: false
     * Codename: upcoming_events
     * Id: 8ceecdd8-183f-4379-a335-078a85d86dc1
     */
    readonly upcoming_events: Elements.LinkedItemsElement<CoreContentType>;
    /**
     * Cloudinary Video
     *
     * Type: modular_content
     * Required: false
     * Codename: cloudinary_video
     * Id: 72877d7e-3334-4b46-8b06-7c5c81c3f97d
     */
    readonly cloudinary_video: Elements.LinkedItemsElement<CloudinaryAsset>;
  },
  "landing_page"
>;

/**
 * Type representing all available element codenames for 🏠 Landing Page
 */
export type LandingPageElementCodenames = "body_copy" | "featured_courses" | "upcoming_events" | "cloudinary_video";

/**
 * Type guard for 🏠 Landing Page
 *
 * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
 * Codename: landing_page
 */
export function isLandingPage(item: CoreContentType | undefined | null): item is LandingPage {
  return item?.system?.type === "landing_page";
}
