
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ➕ Link
 *
 * Id: 68cd41dc-9e88-4237-8ca9-36f7c8712a26
 * Codename: __link
 */
export type Link = CoreContentType<
  LinkElementCodenames,
  {
    /**
     * Display Text
     *
     * Type: text
     * Required: false
     * Codename: display_text
     * Id: a0e0cb46-bd31-44f8-aa85-6d922eb16a8d
     */
    readonly display_text: Elements.TextElement;
    /**
     * Link URL
     *
     * Type: text
     * Required: false
     * Codename: link_url
     * Id: 661806ba-4758-48d4-a421-07ee846019e9
     */
    readonly link_url: Elements.TextElement;
  },
  "__link"
>;

/**
 * Type representing all available element codenames for ➕ Link
 */
export type LinkElementCodenames = "display_text" | "link_url";

/**
 * Type guard for ➕ Link
 *
 * Id: 68cd41dc-9e88-4237-8ca9-36f7c8712a26
 * Codename: __link
 */
export function isLink(item: CoreContentType | undefined | null): item is Link {
  return item?.system?.type === "__link";
}
