
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ➕ Two Column Section
 *
 * Id: 6c1c5324-567d-4148-9546-21503dec14bb
 * Codename: n2_column_section
 */
export type TwoColumnSection = CoreContentType<
  TwoColumnSectionElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: 95149627-658e-40ca-9bc9-803a39152a7c
     */
    readonly title: Elements.TextElement;
    /**
     * Left Column Body
     *
     * Type: rich_text
     * Required: false
     * Codename: left_column_body
     * Id: 960829da-d78d-44a7-9ddd-b1458e2c9af1
     */
    readonly left_column_body: Elements.RichTextElement<CoreContentType>;
    /**
     * Right Column Body
     *
     * Type: rich_text
     * Required: false
     * Codename: right_column_body
     * Id: 189807c1-a8c5-491c-9b4c-d64efda10114
     */
    readonly right_column_body: Elements.RichTextElement<CoreContentType>;
  },
  "n2_column_section"
>;

/**
 * Type representing all available element codenames for ➕ Two Column Section
 */
export type TwoColumnSectionElementCodenames = "title" | "left_column_body" | "right_column_body";

/**
 * Type guard for ➕ Two Column Section
 *
 * Id: 6c1c5324-567d-4148-9546-21503dec14bb
 * Codename: n2_column_section
 */
export function isTwoColumnSection(item: CoreContentType | undefined | null): item is TwoColumnSection {
  return item?.system?.type === "n2_column_section";
}
