
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Link, Page, LandingPage } from "./index.ts";

/**
 * 🏠 Navigation
 *
 * Id: 18196e92-21ab-4207-b1de-8e3a86be5ef7
 * Codename: _navigation
 */
export type Navigation = CoreContentType<
  NavigationElementCodenames,
  {
    /**
     * Header Navigation
     *
     * Type: modular_content
     * Required: false
     * Codename: header_navigation
     * Id: 4616600b-4abf-47f1-82f6-6ebef365a4cd
     */
    readonly header_navigation: Elements.LinkedItemsElement<Link | Page | LandingPage>;
  },
  "_navigation"
>;

/**
 * Type representing all available element codenames for 🏠 Navigation
 */
export type NavigationElementCodenames = "header_navigation";

/**
 * Type guard for 🏠 Navigation
 *
 * Id: 18196e92-21ab-4207-b1de-8e3a86be5ef7
 * Codename: _navigation
 */
export function isNavigation(item: CoreContentType | undefined | null): item is Navigation {
  return item?.system?.type === "_navigation";
}
