
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ➕ Pin Up Section
 *
 * Id: 4a2e11bf-e461-4627-9202-57e7546b17ce
 * Codename: pin_up_section
 */
export type PinUpSection = CoreContentType<
  PinUpSectionElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: e6628393-3c56-4816-86de-5849b8191037
     */
    readonly title: Elements.TextElement;
    /**
     * Body
     *
     * Type: text
     * Required: false
     * Codename: body
     * Id: 7a216acd-9f20-4af2-a629-43348517ad3f
     */
    readonly body: Elements.TextElement;
    /**
     * Color
     *
     * Type: text
     * Required: false
     * Codename: color
     * Id: cc40a5b9-b426-4a73-891d-bfe1e2ecc088
     */
    readonly color: Elements.TextElement;
  },
  "pin_up_section"
>;

/**
 * Type representing all available element codenames for ➕ Pin Up Section
 */
export type PinUpSectionElementCodenames = "title" | "body" | "color";

/**
 * Type guard for ➕ Pin Up Section
 *
 * Id: 4a2e11bf-e461-4627-9202-57e7546b17ce
 * Codename: pin_up_section
 */
export function isPinUpSection(item: CoreContentType | undefined | null): item is PinUpSection {
  return item?.system?.type === "pin_up_section";
}
