
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ➕ Tab
 *
 * Id: 1460769f-b908-4aaf-892c-0cf6d921b4a4
 * Codename: __tabs_section__copy_
 */
export type Tab = CoreContentType<
  TabElementCodenames,
  {
    /**
     * Tab Title
     *
     * Type: text
     * Required: false
     * Codename: tab_title
     * Id: 209eec72-0ca2-4237-b83e-c939947e782d
     */
    readonly tab_title: Elements.TextElement;
    /**
     * Tab Content
     *
     * Type: rich_text
     * Required: false
     * Codename: tab_content
     * Id: 19cb00a9-402a-4d82-95a4-f838f54e1b90
     */
    readonly tab_content: Elements.RichTextElement<CoreContentType>;
  },
  "__tabs_section__copy_"
>;

/**
 * Type representing all available element codenames for ➕ Tab
 */
export type TabElementCodenames = "tab_title" | "tab_content";

/**
 * Type guard for ➕ Tab
 *
 * Id: 1460769f-b908-4aaf-892c-0cf6d921b4a4
 * Codename: __tabs_section__copy_
 */
export function isTab(item: CoreContentType | undefined | null): item is Tab {
  return item?.system?.type === "__tabs_section__copy_";
}
