
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ➕ Accordion
 *
 * Id: 17f46d6e-85e5-4b1c-b413-06de3fcbdcc4
 * Codename: __two_column_section__copy_
 */
export type Accordion = CoreContentType<
  AccordionElementCodenames,
  {
    /**
     * Accordion items
     *
     * Type: rich_text
     * Required: false
     * Codename: accordion_items
     * Id: 04d63205-ee58-42fe-825a-5177c3b6f06e
     * Guidelines: Add a component (or a linked item if reused) for each individual point in this accordion.
     */
    readonly accordion_items: Elements.RichTextElement<CoreContentType>;
  },
  "__two_column_section__copy_"
>;

/**
 * Type representing all available element codenames for ➕ Accordion
 */
export type AccordionElementCodenames = "accordion_items";

/**
 * Type guard for ➕ Accordion
 *
 * Id: 17f46d6e-85e5-4b1c-b413-06de3fcbdcc4
 * Codename: __two_column_section__copy_
 */
export function isAccordion(item: CoreContentType | undefined | null): item is Accordion {
  return item?.system?.type === "__two_column_section__copy_";
}
