
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Honeybook
* Environment: Production
* Id: f58e1d39-d212-0043-310b-606736fbccb8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Link Snippet
 *
 * Id: cb9e7185-2d18-42c8-af4f-3a90ceb97e0d
 * Codename: link
 */
export type LinkSnippet = Snippet<
  LinkSnippetElementCodenames,
  {
    /**
     * Link to content item
     *
     * Type: modular_content
     * Required: false
     * Codename: link__link_to_content_item
     * Id: fff71f1b-9156-445c-a03c-ec00c5b49857
     * Guidelines: Specify a link to an existing item in this project.
     */
    readonly link__link_to_content_item: Elements.LinkedItemsElement<CoreContentType>;
    /**
     * Link to web URL
     *
     * Type: text
     * Required: false
     * Codename: link__link_to_web_url
     * Id: 44d93c4d-9342-4e82-8199-48d871b4b3eb
     * Guidelines: Provide an absolute or relative URL to a web page.
     */
    readonly link__link_to_web_url: Elements.TextElement;
  }
>;

/**
 * Type representing all available element codenames for Link Snippet
 */
export type LinkSnippetElementCodenames = "link__link_to_content_item" | "link__link_to_web_url";
